#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 从提交消息文件中读取提交消息
commit_msg=$(cat "$1")

# 输出调试信息
echo "Commit message: '$commit_msg'"

# 检查是否以 'feat:' 开头
if echo "$commit_msg" | grep -q "^feat:"; then
  echo "Commit message starts with 'feat:'"
  # 如果是以 'feat:' 开头，执行指定命令
  pnpm run build && git add .
else
  echo "Commit message does not start with 'feat:'"
fi